<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>


    <?php
$numbers = array(10,20,30,40,50);
$total = 0;
for($i = 0; $i<=4; $i++)
{
	$total = $total+ $numbers[$i];
}
echo $total;
?>

        
        <script src="" async defer></script>
    </body>
</html>