<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
      <?php
        echo "5  9<br>";
        echo "2610<br>";
        echo "3711<br>";
        echo "4812<br>";
        ?>
        <script src="" async defer></script>
    </body>
</html>