<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
       
    <?php
    
    
     
    $json = '{"Drashan": "Ferrari", "Nitya": "BMW", "Divyesh": "Urus","Hardev":"Mercedeas"}';

    print_r (json_decode($json));
    ?>
        
        <script src="" async defer></script>
    </body>
</html>