<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
       
    <?php

echo '<h3>How can you tell if a number is even or odd without using any Condition or
loop?</h3>';

echo '<h3>Answer:</h3>';

echo '<h4>To check if the number is even or odd without using any condition or loop is<br>
      with the help of (%) operator <br>
      if that number is divisable by 2 and and %2==0 then it is an even number otherwise it is an odd number.</h4>';
    ?>
        
        <script src="" async defer></script>
    </body>
</html>